### ISSUE TITLE
Support Vertx 4.0.0

### ISSUE THREAD

**Issue by haneev** [newrelic/newrelic-java-agent#201]
## Feature Description
Vertx 4.0.0 has been released and it would be cool if NewRelic automatically supports 4.0.0 as well. I am running vertx 4.0.0 and I only see Netty traces in new-relic and I think that is caused by the fact that NewRelic does not add their instrumentation automatically to Vertx 4.0.0 with more detailed information.

## Priority
Really Want

**Comment by tspring** [comment]
Hi @haneev , you're correct that our vertx-core-3.9.0 instrumentation currently does not apply to Vertx-4.0.  There were a significant number of changes in Vertx that we'll have to work out so it may take a little while to get to. That said, it'd be much appreciated if you're willing to provide a PR or gist of an updated instrumentation test like here: https://github.com/newrelic/newrelic-java-agent/tree/main/instrumentation/vertx-core-3.9.0/src/test/java/com/nr/vertx/instrumentation
As the vast majority of the time it takes us to update instrumentation is in catching up on the breaking changes and new usages. Cheers

**Comment by haneev** [comment]
I am working on Vertx 4.0.0, but it keeps failing on:

```
Class io.vertx.core.impl.future.PromiseImpl does not implement the requested interface io.vertx.core.Promise
java.lang.IncompatibleClassChangeError: Class io.vertx.core.impl.future.PromiseImpl does not implement the requested interface io.vertx.core.Promise
```

See my code here: https://github.com/newrelic/newrelic-java-agent/compare/main...sqills:feature/201-vertx-4.0.0?expand=1

Do you have any idea what could cause that? The problem is that it keeps running against vertx 3.9.0 and then the Weaver is crashing. Maybe you can send me into a good direction? @tspring

**Comment by kford-newrelic** [comment]
Closing as a duplicate of #462 (Keeping the latter since it has a bit more details).
